package com.pallavi.designpatterns.builder;

import lombok.Builder;
import lombok.Getter;

/**
 * Immutable value object that represents an email to be sent to a customer.
 * <p>
 * Instances are created using Lombok's {@link Builder} (see {@code CustomerEmail.builder()}).
 * Getters are generated by Lombok's {@link Getter} annotation.
 */
@Getter
@Builder
public class CustomerEmail {
    /**
     * Destination email address for the customer (the "To" address).
     */
    private final String toAddress;

    /**
     * Subject line for the email.
     */
    private final String subject;

    /**
     * Body content of the email.
     */
    private final String body;

    /**
     * Default "From" address used when no explicit fromAddress is provided to the builder.
     */
    @Builder.Default
    private final String fromAddress = "abc@example.com";

    /**
     * Returns a string representation of this {@code CustomerEmail} including
     * the to/from addresses, subject and the (short) body.
     *
     * @return string representation suitable for logging/debugging
     */
    @Override
    public String toString() {
        return "CustomerEmail{" +
                "toAddress='" + toAddress + '\'' +
                ", fromAddress='" + fromAddress + '\'' +
                ", subject='" + subject + '\'' +
                ", body='" + body + '\'' +
                '}';
    }
}
